### ISSUE TITLE
Can't install, sadly! Error message below.

### ISSUE THREAD

**Issue by pm0kjp** [saberry/qualtricsR#2]
Error below.  LMK if you need additional debugging.  Other packages are all up to date.

```
* installing *source* package ‘qualtricsR’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in namespaceExport(ns, exports) : 
  undefined exports: exportQualtricsData
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/qualtricsR’
Error: Command failed (1)
```

**Comment by saberry** [comment]
Ah. Thanks for raising this issue and no additional info required -- it is just an error in my namespace file after a function rename. I will get this fixed tomorrow morning and let you know when it is ready to go.

**Comment by saberry** [comment]
I had a few free minutes, so it should be good to go now. Let me know if anything else pops up.
