### ISSUE TITLE
Error in qualtricsAuth

### ISSUE THREAD

**Issue by avery021** [saberry/qualtricsR#3]
Not sure what I am doing wrong but when I enter my username (email address) and randomTokenCharacters (api token) I receive Error in qualtricsAuth.

Am I missing a step?

**Comment by saberry** [comment]
Can you tell me what specific error you are getting?
Are you getting an error when running the qualtricsAuth function or when you are trying to load the qualtricsAuthInfo.RData file?

**Comment by avery021** [comment]
I am getting the error when I run the qualtricsAuth function. The error is error in qulatricsAuth.

It wont create the qualtricsAuthInfo.RData file

**Comment by saberry** [comment]
Just to make sure, your code looks something like the following:

qualtricsAuth("username@place.edu#brand", "longString")

You might also specify the file location and name explicitly, if that is causing any issue.

**Comment by saberry** [comment]
It appears that I also need to include the quotes in the documentation!

**Comment by avery021** [comment]
I must have not included quotes the first time, it is working now. Thanks.

**Comment by saberry** [comment]
Well it sure would have helped if the fool who wrote the documentation would have done it correctly!

Glad it works and let me know if anything else pops up.
